refactor(Calcified): use `Int`s instead of `Byte`s for port numbers
Dairy-Foundation/Dairy pull request #5
Opened 2024-03-13 03:24 UTC by dr-hextanium

in order for better Java compatibility (remove the need for casting to byte which was noisy), resolves #4

2024-03-13 03:56 UTC, dr-hextanium commented
i see what i messed up here

2024-03-13 03:59 UTC, dr-hextanium commented
TODO: remove the gitconfig stuff and then it should actually be fine

2024-03-13 14:54 UTC, Froze-N-Milk requested changes
1. See comments on .gitmodules
2. Resolve conflict in Calcified
3. Update java overview to no longer cast to byte

2024-03-13 14:54 UTC, Froze-N-Milk commented on .gitmodules
revert changes to https and change all to ssh

2024-03-15 01:54 UTC, Froze-N-Milk approved these changes

2024-03-15 01:54 UTC, merged